config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get 'pages/home'
  get 'pages/about_us'

  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :caravans, only: [:new, :create, :update, :edit, :destroy]
    get 'caravans/:id', to: 'caravans#show_own', as: :own_caravan
    get 'caravans', to: 'caravans#index_own', as: :own_caravans
    resources :rentals, only: [:index, :show]
  end

  resources :caravans, only: [:show, :index] do
    resources :rentals, only: [:new, :create]
  end

  resources :rentals, only: [:update, :destroy]

end

app/models/caravan.rb
class Caravan < ActiveRecord::Base
  belongs_to :user
  has_many :caravan_images, dependent: :destroy
  has_many :rentals

  validates :title, presence: true, length: { minimum: 10 }
  validates :street, :city, :zip_code, :country, :capacity, :price, :description, presence: true
  validates :tv, :shower, :coffee_machine, :kitchen, :wifi, inclusion: { in: [true, false] }

  mount_uploader :photo, PhotoUploader

  geocoded_by :address

  def address
    [street, city, zip_code, country].compact.join(', ')
  end

  after_validation :geocode, if: :address_changed?

  def address_changed?
    street_changed? || city_changed? || country_changed? || zip_code_changed?
  end

end

app/models/caravan_image.rb
class CaravanImage < ActiveRecord::Base
  belongs_to :caravan

  validates :url, presence: true
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :caravan
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :caravans, dependent: :destroy
  has_many :rentals
  mount_uploader :photo, PhotoUploader
  # validates :first_name, :last_name, presence: true
  # validates :description, :gender, :street, :city, :zip_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/caravans_controller.rb
class CaravansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_caravan, only: [:show, :edit, :update]
  before_action :find_user, only: [:create, :new, :show_own, :index_own, :edit, :update, :destroy]
  before_action :user_caravan, only: [:show_own, :edit, :destroy]

  def index
    @caravans = Caravan.all

    @search = params[:search][:address]
    @radius = params[:search][:radius]

    @caravans = @caravans.near(@search, @radius) if @search.present? && @radius.present?

    @markers = Gmaps4rails.build_markers(@caravans) do |caravan, marker|
      marker.lat caravan.latitude
      marker.lng caravan.longitude
    end
  end

  def index_own
    @caravans = @user.caravans
  end

  def show
    @rental = Rental.new
  end

  def show_own
  end

  def new
    @caravan = Caravan.new
  end

  def edit
  end

  def create
    @caravan = @user.caravans.build(caravan_params)
    @caravan.save
    if @caravan.save
      redirect_to user_own_caravan_path(@user, @caravan)
    else
      render :new
    end
  end

  def update
    if @caravan.update(caravan_params)
      redirect_to user_caravan_path(@user, @caravan)
    else
      render :edit
    end
  end

  def destroy
    @caravan.destroy
    redirect_to user_own_caravans_path(@user)
  end

  private

  def user_caravan
    @caravan = @user.caravans.find(params[:id])
  end

  def find_user
    @user = current_user
  end

  def set_caravan
    @caravan = Caravan.find(params[:id])
  end

  def caravan_params
    params.require(:caravan).permit(:title, :description, :capacity, :price, :street, :city, :country, :zip_code, :tv, :shower, :coffee_machine, :kitchen, :wifi, :photo ,:photo_cache)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about_us]
  def home
    @sample_caravans = []
    if Caravan.count >= 1
      @sample_caravan1 = sample_caravan
      @sample_caravans << @sample_caravan1
    end
    if Caravan.count >= 2
      @sample_caravan2 = sample_caravan
      until @sample_caravan1 != @sample_caravan2
        @sample_caravan2 = sample_caravan
      end
      @sample_caravans << @sample_caravan2
    end
    if Caravan.count >= 3
      @sample_caravan3 = sample_caravan
      until (@sample_caravan1 != @sample_caravan2) && (@sample_caravan1 != @sample_caravan3) && (@sample_caravan2 != @sample_caravan3)
        @sample_caravan3 = sample_caravan
      end
      @sample_caravans << @sample_caravan3
    end
    render layout: 'home'
  end

  def about_us
  end

  private
  def sample_caravan
    Caravan.all.sample
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :find_caravan, only: [:new, :create]
  before_action :set_rental, only: [:show, :destroy, :update]

  def index
    @rentals = current_user.rentals.all
  end

  def show
  end

  def index_own
  end

  def new
    @rental = Rental.new
  end

  def create
    @rental = @caravan.rentals.new(rental_params)
    @rental.user = current_user
    @rental.save
    @nb_of_days = (@rental.end_date - @rental.start_date)
    @rental.price = (@rental.price * @nb_of_days)
    @rental.save
    if @rental.save
      redirect_to user_path(current_user) + "#bookings"
    else
      render :new
    end
  end

  def update
    @rental.validated = rental_params[:validated]
    @rental.save
    redirect_to user_path(current_user) + "#bookings"
  end


  def destroy
    @rental.destroy
    redirect_to user_path(current_user) + "#bookings"
  end

  private
  def set_rental
    @rental = Rental.find(params[:id])
  end

  def find_caravan
    @caravan = Caravan.find(params[:caravan_id])
  end

  def rental_params
    params.require(:rental).permit(:price, :start_date, :end_date, :validated, :caravan_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user

  def show
    @caravans = current_user.caravans.all
    @rentals = current_user.rentals.all
    @caravan = Caravan.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    if user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :gender, :street, :city, :zip_code, :email, :password, :photo, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caravans_helper.rb
module CaravansHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/caravans/_index_own.html.erb
 <div class="container padded">
  <% @caravans.each_slice(3) do |caravans| %>
    <div class="row">
     <% caravans.each do |caravan| %>
      <div class="col-xs-12 col-md-4">
        <div class="card">
          <%= cl_image_tag caravan.photo, :height=>222, :crop=>:thumb, class: "card-image" %>
            <div class="card-price inline"><%= caravan.price.to_s + "€" %></div>
            <div class="card-description">
              <h3><%= caravan.title %></h3>
              <p><%= caravan.city %></p>
            </div>
            <%= cl_image_tag caravan.user.photo, :radius=>"max", :width=>50, :height=>50, :crop=>:thumb, :gravity=>:face, class: "card-user avatar-large" %>
            <%= link_to caravan.title, user_own_caravan_path(current_user, caravan), class: "card-link" %>
          </div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/caravans/edit.html.erb
<%= render "shared/caravan_form" %>

app/views/caravans/index.html.erb
<div class="container-fluid">
  <div class="text-center">
    <h1><strong>Caravans around <%= @search %></strong></h1>
    <br>
  </div>
  <div class="row">
    <div class="col-sm-6">
     <div class="container">
      <% @caravans.each_slice(2) do |caravans| %>
      <div class="row" style="margin-bottom: 30px;">
       <% caravans.each do |caravan| %>
       <div class="col-sm-3">
        <div class="card">
          <%= cl_image_tag caravan.photo, :height=>222, :crop=>:thumb, class: "card-image" %>
          <div class="card-price inline"><%= caravan.price.to_s + "€" %></div>
          <div class="card-description">
            <h3><%= caravan.title %></h3>
            <p><%= caravan.city %></p>
          </div>
          <%= cl_image_tag caravan.user.photo, :radius=>"max", :width=>50, :height=>50, :crop=>:thumb, :gravity=>:face, class: "card-search avatar-large" %>
          <%= link_to caravan.title, caravan_path(caravan), class: "card-link" %>
        </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-6">
    <div id="map" style="width: 100%; height: 600px;"></div>
    <% content_for(:after_js) do %>
    <%= javascript_tag do %>
    $(document).on('ready', function() {
    handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function(){
    markers = handler.addMarkers(<%= raw @markers.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
})
<% end %>
<% end %>
</div>
</div>
</div>

app/views/caravans/index_own.html.erb
<div class="text-center"><h1>All my caravans</h1></div>
 <div class="container ">
  <% @caravans.each_slice(3) do |caravans| %>
    <div class="row">
     <% caravans.each do |caravan| %>
    <div class="col-xs-12 col-md-4">
    <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= caravan.photo %>');background-size: cover;">
    <div class="card-category"></div>
    <div class="card-description">
      <h2><%= caravan.description %> </h2>
    </div>
      <%= link_to "", user_own_caravan_path(@user,caravan), class: "card-link" %>
  </div>
</div>
  <% end %>
</div>
  <% end %>
</div>
<br>
<div class="button-back">
  <%= link_to "Back to my profile", user_path(@user), class:"btn btn-primary" %>
</div>

<%= link_to "Bookings", user_rentals_path(current_user) %>

app/views/caravans/new.html.erb
<%= render "shared/caravan_form" %>

app/views/caravans/show.html.erb
<div class="caravan-banner" style="background: url('<%= @caravan.photo %>');">
  <div class="caravan-rent">

    <button data-toggle="modal" data-target="#new-rental" class="btn btn-danger">Book it</button>
  </div>
  <div class="caravan-banner-content">
    <h3><%= @caravan.title  %> <span class="label label-default"><%= @caravan.price %> €</span></h3>
  </div>
</div>

<div class="container padded">
  <div class="panel panel-primary">
    <div class="panel-heading">About the caravan</div>
    <div class="panel-body">
      <%= @caravan.description %>
      <%= @caravan.capacity %>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">Caravan equipment</div>
    <div class="panel-body">
    <div class="list-equipment">
      <ul class="list-inline">
       <li> <% if @caravan.tv %>
        <i class="fa fa-television">   TV included</i>
        <% end %>
      </li>
      <li>
        <% if @caravan.wifi %>
        <i class="fa fa-wifi">   Wifi included</i>
        <% end %>
       </li>
       <li>
        <% if @caravan.shower %>
        <i class="fa fa-cloud">   Shower included</i>
        <% end %>
       </li>
       <li>
        <% if @caravan.coffee_machine %>
        <i class="fa fa-coffee">   Coffee machine included</i>
        <% end %>
       </li>
       <li>
        <% if @caravan.kitchen %>
        <i class="fa fa-spoon">   Kitchen included</i>
        <% end %>
       </li>
      </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">Caravan location</div>
    <div class="container" style="margin: 5px 0;">
      <div class="row">
       <div class="col-sm-5">
        <div class="panel-body">
          <%= @caravan.street %>
          <%= @caravan.city %>
          <%= @caravan.zip_code %>
          <%= @caravan.country %>
        </div>
      </div>
      <div class="col-sm-7">
       <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=550x300&sensor=false&maptype=roadmap&markers=color:red|#{@caravan.address}" %>
     </div>
   </div>
 </div>
</div>


<div class="modal fade" tabindex="-1" role="dialog" id="new-rental">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #53443F">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" style="color: #FFF">Submit your booking request</h4>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <%= render "rentals/new", caravan: @caravan, rental: @rental %>
            </div>
          </div>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/caravans/show_own.html.erb
<div class="caravan-banner" style="background: url('<%= @caravan.photo %>');">
    <div class="caravan-banner-content">
      <h3><%= @caravan.title  %> <span class="label label-default"><%= @caravan.price %> €</span></h3>
    </div>
</div>

<div class="container padded">
  <div class="panel panel-primary">
    <div class="panel-heading">About the caravan</div>
    <div class="panel-body">
      <%= @caravan.description %>
      <%= @caravan.capacity %>
    </div>
  </div>
    <div class="panel panel-primary">
      <div class="panel-heading">Caravan equipment</div>
      <div class="panel-body">
        <% if @caravan.tv %>
          <i class="fa fa-television">   TV included</i>
        <% end %>
        <% if @caravan.wifi %>
          <i class="fa fa-wifi">   Wifi included</i>
        <% end %>
        <% if @caravan.shower %>
          <i class="fa fa-cloud">   Shower included</i>
        <% end %>
        <% if @caravan.coffee_machine %>
          <i class="fa fa-coffee">   Coffee machine included</i>
        <% end %>
        <% if @caravan.kitchen %>
          <i class="fa fa-spoon">   Kitchen included</i>
        <% end %>
      </div>
    </div>
    <div class="panel panel-primary">
      <div class="panel-heading">Caravan location</div>
        <div class="container" style="margin: 5px 0;">
          <div class="row">
           <div class="col-sm-5">
            <div class="panel-body">
              <%= @caravan.street %>
              <%= @caravan.city %>
              <%= @caravan.zip_code %>
              <%= @caravan.country %>
            </div>
          </div>
          <div class="col-sm-7">
           <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=550x300&sensor=false&maptype=roadmap&markers=color:red|#{@caravan.address}" %>
         </div>
         </div>
        </div>
        </div>
    </div>
  <div class="text-center" style="margin-bottom: 25px;">
    <%= link_to "Edit information", edit_user_caravan_path(@user, @caravan), class: "btn btn-primary" %>
    <%= link_to "Back to profile", user_path(@user), class: "btn btn-primary" %>
  </div>

</div>

app/views/pages/about_us.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/rentals/_index.html.erb
<div class="container">
  <h2><strong>Your bookings</strong></h2>
  <% if @rentals == [] %>
    <p>You haven't made any bookings yet<p>
  <% else %>
    <div class="row">
      <% @rentals.each do |rental| %>
        <div class="col-sm-4">
          <div class="booking-card">
            <div id="card-blur" class="<%= "validation-pending" unless rental.validated %>">
              <div class="booking-card-header">
                <h3><%= link_to rental.caravan.title, caravan_path(rental.caravan) %></h3>
              </div>
              <div class="booking-card-content">
                <p><strong>Booking made by: </strong><%= "#{rental.user.first_name} #{rental.user.last_name}" %></p>
                <p><strong>From: </strong><%= "#{rental.start_date}" %></p>
                <p><strong>To: </strong><%= "#{rental.end_date}" %></p>
                <p><strong>Overall price: </strong><%= "#{rental.price}€" %></p>
                <%= link_to "Cancel my reservation", rental_path(rental), method: :delete, class: "btn btn-danger" %>
              </div>
            </div>
             <% if rental.validated == false %>
                <div class="validation-status text-center">
                  <h3><strong>Validation pending</strong></h3>
                </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="container">
  <h2><strong>Bookings placed on my caravans</strong></h2>
    <% current_user.caravans.each do |caravan| %>
      <% if caravan.rentals == [] %>
      <% else %>
        <div class="row">
          <% caravan.rentals.each do |rental| %>
            <div class="col-sm-4">
              <div class="booking-card">
                <div class="booking-card-header">
                  <h3><%= link_to rental.caravan.title, caravan_path(rental.caravan) %></h3>
                </div>
                <div class="booking-card-content">
                  <p><strong>Booking made by: </strong><%= "#{rental.user.first_name} #{rental.user.last_name}" %></p>
                  <p><strong>From: </strong><%= "#{rental.start_date}" %></p>
                  <p><strong>To: </strong><%= "#{rental.end_date}" %></p>
                  <p><strong>Overall price: </strong><%= "#{rental.price}€" %></p>
                  <% if rental.validated == false %>
                    <%= simple_form_for rental do |f| %>
                      <%= f.input :validated, as: :hidden, input_html: { value: true } %>
                      <%= f.button :submit, "Validate", class: "btn btn-success" %>
                    <% end %>
                  <% else %>
                    <i class="fa fa-check-square-o">  Validated</i>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/rentals/index.html.erb
<div>
  <h2>Your bookings</h2>
  <ul>
    <% if @rentals == [] %>
      <p>You haven't made any bookings yet<p>
    <% else %>
      <% @rentals.each do |rental| %>
        <h3><%= link_to rental.caravan.title, caravan_path(rental.caravan) %></h3>
        <p><%= "From: #{rental.start_date}, To: #{rental.end_date}" %></p>
        <p><%= "Overall price: #{rental.price}€" %></p>
        <%= link_to "Cancel my reservation", rental_path(rental), method: :delete %>
      <% end %>
    <% end %>
  </ul>
</div>

<div>
  <h2>Bookings placed on my caravans</h2>
  <ul>
    <% current_user.caravans.each do |caravan| %>
      <% if caravan.rentals == [] %>
        <p>No bookings have been placed on your caravans yet<p>
      <% else %>
        <% caravan.rentals.each do |rental| %>
          <li>
            <h3><%= link_to rental.caravan.title, caravan_path(rental.caravan) %></h3>
            <p><%= "Booking made by: #{rental.user.first_name} #{rental.user.last_name}" %></p>
            <p><%= "From: #{rental.start_date}, To: #{rental.end_date}" %></p>
            <p><%= "Overall price: #{rental.price}€" %></p>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/rentals/show.html.erb
<%= @rental.price %>
<%= @rental.start_date %>
<%= @rental.end_date %>
<%= @rental.caravan.title %>

<%= link_to "All my bookings", user_rentals_path(current_user) %>
<%= link_to "Delete this booking", rental_path(@rental), method: :delete %>

app/views/shared/_caravan_cards.html.erb
<div class="card">
<%= cl_image_tag caravan.photo, :height=>222, :crop=>:thumb, class: "card-image" %>
  <div class="card-price inline"><%= caravan.price.to_s + "€" %></div>
  <div class="card-description">
    <h3><%= caravan.title %></h3>
    <p><%= caravan.city %></p>
  </div>
  <%= cl_image_tag caravan.user.photo, :radius=>"max", :width=>50, :height=>50, :crop=>:thumb, :gravity=>:face, class: "card-user avatar-large" %>
  <%= link_to caravan.title, caravan_path(caravan), class: "card-link" %>
</div>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <div>
    <p>Join the tribe</p>
  </div>
  <div class="inline">
    <i class="fa fa-facebook-official"></i>
    <i class="fa fa-twitter"></i>
    <i class="fa fa-instagram"></i>
    <i class="fa fa-pinterest"></i>
  </div>
</div>

app/views/shared/_form_navbar.html.erb
<div class="form-inline">
  <%= simple_form_for :search, url: caravans_path, method: :get do |f| %>
    <%= f.input :address, label: false, placeholder: "Where are you going?", input_html: { value: @search } %>
    <%= f.input :radius, collection: [50, 100, 150], selected: 50, label: false, input_html: { value: @radius  } %>
    <%= f.button :submit, "GO !", class:"btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-home navbar-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand navbar-wagon-brand-home" do %>
    <%= render 'shared/logo' %>
  <% end %>
   <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= render 'shared/form_navbar' %>
  <!-- Right Navigation -->


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>

      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo,:width=>30, :height=>30, :crop=>:thumb, :gravity=>:face, class: "dropdown-toggle avatar", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to  root_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".top_call_to_action", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Sign-up text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "About us", pages_about_us_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar-wagon navbar-wagon-home">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand navbar-wagon-brand-home" do %>
    <%= render 'shared/logo' %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo,:width=>30, :height=>30, :crop=>:thumb, :gravity=>:face, class: "dropdown-toggle avatar", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".top_call_to_action", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Sign-up text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "About us", pages_about_us_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div class="container form-background" style="max-width: 900px; border-radius: 3px;">
  <div class="form-inline form-home">
    <%= simple_form_for :search, url: caravans_path, method: :get do |f| %>
      <%= f.input :address, label: false, placeholder: "Where ?" %>
      <%= f.input :radius, collection: [50, 100, 150], selected: 50, label: false %>
      <%= f.input :start_date, as: :string, input_html: {type: :date}, label: "FROM " %>
      <%= f.input :end_date, as: :string, input_html: {type: :date}, label: " TO " %>
      <%= f.button :submit, "Search", class:"btn btn-warning" %>
    <% end %>
  </div>
</div>